nodeLinker: pnp

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
    '@craco/craco@*':
        peerDependencies:
            '@types/node': '*'
            'typescript': '*'
    eslint-config-react-app@*:
        peerDependencies:
            '@babel/plugin-syntax-flow': '*'
            '@babel/plugin-transform-react-jsx': '*'
    babel-preset-react-app@*:
        dependencies:
            '@babel/plugin-proposal-private-property-in-object': '*'
    react-dev-utils@*:
        peerDependencies:
            'typescript': '*'
            'webpack': '*'
    react-scripts@*:
        peerDependencies:
            '@babel/plugin-syntax-flow': '*'
            '@babel/plugin-transform-react-jsx': '*'
            'autoprefixer': '*'
